language: python
sudo: required
python:
  - "2.7"
install:
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password $MYSQL_ROOT_PASSWORD'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD'
  - sudo apt-get update
  - sudo apt-get -y install python python-pip libjpeg-dev python-dev libmysqlclient-dev memcached tmux python-nose mysql-server mysql-client
  - sudo pip install Flask mysql-python Flask-SQLAlchemy SQLAlchemy gunicorn requests voluptuous Pillow markdown2 onetimepass pyqrcode python-memcached nose
script:
  - export SQLALCHEMY_DATABASE_URI=mysql://root:password@localhost/openctf
  - py.test
services:
  - mysql
env:
  - MYSQL_ROOT_PASSWORD=password
notifications:
  email: false