language: python
sudo: required
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install python python-pip libjpeg-dev python-dev libmysqlclient-dev memcached tmux python-nose mysql-client
  - sudo pip install Flask mysql-python Flask-SQLAlchemy SQLAlchemy gunicorn requests voluptuous Pillow markdown2 onetimepass pyqrcode python-memcached nose
script:
  - "gunicorn --bind 0.0.0.0:8000 -w 4 app:app"
  - nosetests
services:
  - mysql
notifications:
  email: false