language: python
sudo: required
python:
  - "2.7"
install:
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password $MYSQL_ROOT_PASSWORD'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD'
  - sudo apt-get update
  - sudo apt-get -y install libjpeg-dev libmysqlclient-dev memcached tmux mysql-server mysql-client
  - sudo pip install -r api/requirements.txt
  - py.test --version
script:
  - export SQLALCHEMY_DATABASE_URI=mysql://root:password@localhost/openctf
  - python -c 'import pip;installed_packages = pip.get_installed_distributions();installed_packages_list = sorted(["%s==%s" % (i.key, i.version);for i in installed_packages]);print(installed_packages_list)'
  - py.test
services:
  - mysql
env:
  - MYSQL_ROOT_PASSWORD=password
notifications:
  email: false
