openctf:
  build: nginx
  links:
    - api
  ports:
    - "80:80"
  volumes:
    - ./nginx/web:/srv/http/ctf

api:
  build: api
  links:
    - db
  expose:
    - 8000
  volumes:
    - ./api:/openctf
  entrypoint: chmod +x wait-for-it.sh && ./wait-for-it.sh db_1

db:
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=openctf
  expose:
    - 3306
  image: mysql